remove prefetch_related(city__state) causing error whitespace
ValueError: 'city__state' does not resolve to an item that supports
prefetching - this is an invalid parameter to prefetch_related().